from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

# Import model modules eagerly so Django registers every model class when the
# app loads. The lazy export mechanism below is fine for attribute access, but
# not sufficient for ORM relation resolution across modules.
_REGISTERED_MODEL_MODULES = (
    import_module(".card", __name__),
    import_module(".card_back", __name__),
    import_module(".card_group", __name__),
    import_module(".content_version", __name__),
    import_module(".card_version", __name__),
    import_module(".parse_flag", __name__),
    import_module(".deck", __name__),
    import_module(".deck_tag", __name__),
    import_module(".developer_data", __name__),
    import_module(".notification", __name__),
    import_module(".user_access_request", __name__),
    import_module(".user_activity", __name__),
    import_module(".import_job", __name__),
    import_module(".metadata", __name__),
    import_module(".template", __name__),
    import_module(".tts_card_sheet", __name__),
    import_module(".worker_heartbeat", __name__),
)

if TYPE_CHECKING:
    from .base import now_utc
    from .card import (
        ACTIVE_CARD_LIFECYCLE_STATUS,
        ALL_CARD_POOLS_SCOPE,
        ALL_CARD_LIFECYCLE_FILTER,
        BLOOD_CARD_FACTION,
        BOON_CARD_ROLE,
        BOSS_CARD_ROLE,
        CARD_FACTION_CHOICES,
        CARD_FACTION_DEFINITIONS,
        CARD_FACTIONS,
        CARD_LIFECYCLE_FILTER_VALUES,
        CARD_LIFECYCLE_STATUSES,
        CARD_POOL_CHOICES,
        CARD_POOL_DEFINITIONS,
        CARD_POOLS,
        CARD_ROLE_CHOICES,
        CARD_ROLE_DEFINITIONS,
        CARD_ROLE_FILTER_DEFINITIONS,
        CARD_ROLE_FILTER_VALUES,
        CARD_ROLES,
        DEFAULT_CARD_LIFECYCLE_FILTER,
        DEFAULT_CARD_POOL,
        DARKNESS_CARD_FACTION,
        DEPRECATED_CARD_LIFECYCLE_STATUS,
        EVIL_CARD_POOL,
        EVENT_CARD_ROLE,
        HERO_CARD_ROLE,
        LOCATION_CARD_ROLE,
        NEUTRAL_CARD_POOL,
        PLAYER_CARD_POOL,
        PLAYER_CARD_POOL_SCOPE,
        ORDER_CARD_FACTION,
        SHOP_ITEM_CARD_ROLE,
        STANDARD_CARD_ROLE,
        Card,
        CardAlias,
        CardFaction,
        CardFactionAssignment,
        CardFactionDefinition,
        CardIdentityPoolLock,
        CardLifecycleCarrier,
        CardLifecycleFilter,
        CardLifecycleStatus,
        CardMergeRedirect,
        CardPool,
        CardPoolDefinition,
        CardPoolScope,
        CardRole,
        CardRoleAssignment,
        CardRoleDefinition,
        CardRoleFilter,
        CardRoleFilterDefinition,
        active_card_lifecycle_q,
        card_faction_identity_key,
        card_faction_keys,
        card_has_role,
        card_has_faction,
        card_is_deprecated,
        card_is_visible_for_lifecycle,
        card_lifecycle_filter_q,
        card_role_keys,
        filter_queryset_by_card_lifecycle,
        is_card_pool,
        is_card_lifecycle_status,
        normalize_card_lifecycle_filter,
        normalize_card_factions,
        normalize_card_roles,
    )
    from .card_back import CardBack
    from .card_group import CardGroup, CardGroupMember
    from .content_version import ContentVersion
    from .card_version import CardVersion, CardVersionImage, ParseResult
    from .parse_flag import (
        PARSE_FLAG_ITEM_DISMISSED,
        PARSE_FLAG_ITEM_OPEN,
        PARSE_FLAG_ITEM_RESOLVED,
        PARSE_FLAG_ITEM_STATUSES,
        PARSE_FLAG_PROPERTY_KEYS,
        CardVersionParseFlag,
        CardVersionParseFlagItem,
    )
    from .deck import (
        Deck,
        DeckCreation,
        DeckDifficulty,
        DeckEntry,
        DeckSideboard,
        DeckSideboardEntry,
        DeckVisibility,
    )
    from .deck_tag import (
        DECK_TAG_KINDS,
        DECK_TAG_SUGGESTION_STATUSES,
        DeckTag,
        DeckTagAssignment,
        DeckTagKind,
        DeckTagSuggestion,
        DeckTagSuggestionDeck,
        DeckTagSuggestionStatus,
    )
    from .developer_data import (
        DeveloperDataBuild,
        DeveloperDataBuildStatus,
        DeveloperDataDownloadGrant,
    )
    from .notification import (
        NOTIFICATION_EVENT_DECK_CARD_VERSION_CHANGED,
        NOTIFICATION_EVENT_PARSE_FLAG_ITEM_REVIEWED,
        NOTIFICATION_STATUS_ALL,
        NOTIFICATION_STATUS_FILTERS,
        NOTIFICATION_STATUS_READ,
        NOTIFICATION_STATUS_UNREAD,
        UserNotification,
    )
    from .user_access_request import (
        ACCESS_REQUEST_STATUS_APPROVED,
        ACCESS_REQUEST_STATUS_DECLINED,
        ACCESS_REQUEST_STATUS_FILTER_ALL,
        ACCESS_REQUEST_STATUS_FILTERS,
        ACCESS_REQUEST_STATUS_PENDING,
        ACCESS_REQUEST_STATUSES,
        UserAccessRequest,
    )
    from .user_activity import UserActivity
    from .import_job import (
        CardClassificationInferenceEvidence,
        CardFactionInferenceEvidence,
        CardRoleInferenceEvidence,
        ClassificationRuleEvidence,
        ClassificationSourceEvidence,
        ImportClassificationMode,
        ImportJob,
        ImportJobItem,
        ImportJobStatus,
    )
    from .metadata import (
        CARD_CLASSIFICATION_SOURCE_KIND_CHOICES,
        CARD_CLASSIFICATION_SOURCE_TAG,
        CARD_CLASSIFICATION_SOURCE_TYPE,
        CARD_CLASSIFICATION_TARGET_FACTION,
        CARD_CLASSIFICATION_TARGET_KIND_CHOICES,
        CARD_CLASSIFICATION_TARGET_ROLE,
        CardClassificationRule,
        CardClassificationSourceKind,
        CardClassificationTargetKind,
        CardVersionMetadataSuggestion,
        CardVersionKeyword,
        CardVersionSymbol,
        CardVersionTag,
        CardVersionType,
        Keyword,
        MetadataSuggestion,
        Symbol,
        Tag,
        Type,
    )
    from .template import Template
    from .tts_card_sheet import (
        TTS_CARD_SHEET_CAPACITY,
        TTS_CARD_SHEET_COLUMNS,
        TTS_CARD_SHEET_LAYOUT_VERSION,
        TTS_CARD_SHEET_ROWS,
        TtsCardSheet,
        TtsCardSheetSlot,
    )
    from .worker_heartbeat import WorkerActivity, WorkerHeartbeat

_EXPORTS = {
    "now_utc": ".base",
    "ImportJobStatus": ".import_job",
    "ImportClassificationMode": ".import_job",
    "CardClassificationInferenceEvidence": ".import_job",
    "CardFactionInferenceEvidence": ".import_job",
    "CardRoleInferenceEvidence": ".import_job",
    "ClassificationRuleEvidence": ".import_job",
    "ClassificationSourceEvidence": ".import_job",
    "ImportJob": ".import_job",
    "ImportJobItem": ".import_job",
    "Card": ".card",
    "ALL_CARD_POOLS_SCOPE": ".card",
    "CardBack": ".card_back",
    "CardAlias": ".card",
    "BLOOD_CARD_FACTION": ".card",
    "BOON_CARD_ROLE": ".card",
    "BOSS_CARD_ROLE": ".card",
    "CARD_FACTION_CHOICES": ".card",
    "CARD_FACTION_DEFINITIONS": ".card",
    "CARD_FACTIONS": ".card",
    "CARD_POOL_CHOICES": ".card",
    "CARD_POOL_DEFINITIONS": ".card",
    "CARD_POOLS": ".card",
    "CARD_ROLE_CHOICES": ".card",
    "CARD_ROLE_DEFINITIONS": ".card",
    "CARD_ROLE_FILTER_DEFINITIONS": ".card",
    "CARD_ROLE_FILTER_VALUES": ".card",
    "CARD_ROLES": ".card",
    "DEFAULT_CARD_POOL": ".card",
    "DARKNESS_CARD_FACTION": ".card",
    "EVIL_CARD_POOL": ".card",
    "EVENT_CARD_ROLE": ".card",
    "HERO_CARD_ROLE": ".card",
    "LOCATION_CARD_ROLE": ".card",
    "NEUTRAL_CARD_POOL": ".card",
    "PLAYER_CARD_POOL": ".card",
    "PLAYER_CARD_POOL_SCOPE": ".card",
    "ORDER_CARD_FACTION": ".card",
    "SHOP_ITEM_CARD_ROLE": ".card",
    "STANDARD_CARD_ROLE": ".card",
    "ACTIVE_CARD_LIFECYCLE_STATUS": ".card",
    "ALL_CARD_LIFECYCLE_FILTER": ".card",
    "CARD_LIFECYCLE_FILTER_VALUES": ".card",
    "CARD_LIFECYCLE_STATUSES": ".card",
    "DEFAULT_CARD_LIFECYCLE_FILTER": ".card",
    "DEPRECATED_CARD_LIFECYCLE_STATUS": ".card",
    "CardLifecycleFilter": ".card",
    "CardLifecycleCarrier": ".card",
    "CardLifecycleStatus": ".card",
    "CardIdentityPoolLock": ".card",
    "CardMergeRedirect": ".card",
    "CardPool": ".card",
    "CardPoolDefinition": ".card",
    "CardPoolScope": ".card",
    "CardFaction": ".card",
    "CardFactionAssignment": ".card",
    "CardFactionDefinition": ".card",
    "CardRole": ".card",
    "CardRoleAssignment": ".card",
    "CardRoleDefinition": ".card",
    "CardRoleFilter": ".card",
    "CardRoleFilterDefinition": ".card",
    "active_card_lifecycle_q": ".card",
    "card_faction_identity_key": ".card",
    "card_faction_keys": ".card",
    "card_has_faction": ".card",
    "card_has_role": ".card",
    "card_is_deprecated": ".card",
    "card_is_visible_for_lifecycle": ".card",
    "card_lifecycle_filter_q": ".card",
    "card_role_keys": ".card",
    "filter_queryset_by_card_lifecycle": ".card",
    "is_card_pool": ".card",
    "is_card_lifecycle_status": ".card",
    "normalize_card_lifecycle_filter": ".card",
    "normalize_card_factions": ".card",
    "normalize_card_roles": ".card",
    "CardGroup": ".card_group",
    "CardGroupMember": ".card_group",
    "ContentVersion": ".content_version",
    "CardVersion": ".card_version",
    "CardVersionImage": ".card_version",
    "ParseResult": ".card_version",
    "PARSE_FLAG_ITEM_DISMISSED": ".parse_flag",
    "PARSE_FLAG_ITEM_OPEN": ".parse_flag",
    "PARSE_FLAG_ITEM_RESOLVED": ".parse_flag",
    "PARSE_FLAG_ITEM_STATUSES": ".parse_flag",
    "PARSE_FLAG_PROPERTY_KEYS": ".parse_flag",
    "CardVersionParseFlag": ".parse_flag",
    "CardVersionParseFlagItem": ".parse_flag",
    "Deck": ".deck",
    "DeckCreation": ".deck",
    "DeckDifficulty": ".deck",
    "DeckVisibility": ".deck",
    "DeckEntry": ".deck",
    "DeckSideboard": ".deck",
    "DeckSideboardEntry": ".deck",
    "DECK_TAG_KINDS": ".deck_tag",
    "DECK_TAG_SUGGESTION_STATUSES": ".deck_tag",
    "DeckTag": ".deck_tag",
    "DeckTagAssignment": ".deck_tag",
    "DeckTagKind": ".deck_tag",
    "DeckTagSuggestion": ".deck_tag",
    "DeckTagSuggestionDeck": ".deck_tag",
    "DeckTagSuggestionStatus": ".deck_tag",
    "DeveloperDataDownloadGrant": ".developer_data",
    "DeveloperDataBuild": ".developer_data",
    "DeveloperDataBuildStatus": ".developer_data",
    "UserNotification": ".notification",
    "NOTIFICATION_EVENT_DECK_CARD_VERSION_CHANGED": ".notification",
    "NOTIFICATION_EVENT_PARSE_FLAG_ITEM_REVIEWED": ".notification",
    "NOTIFICATION_STATUS_ALL": ".notification",
    "NOTIFICATION_STATUS_FILTERS": ".notification",
    "NOTIFICATION_STATUS_READ": ".notification",
    "NOTIFICATION_STATUS_UNREAD": ".notification",
    "UserAccessRequest": ".user_access_request",
    "ACCESS_REQUEST_STATUS_APPROVED": ".user_access_request",
    "ACCESS_REQUEST_STATUS_DECLINED": ".user_access_request",
    "ACCESS_REQUEST_STATUS_FILTER_ALL": ".user_access_request",
    "ACCESS_REQUEST_STATUS_FILTERS": ".user_access_request",
    "ACCESS_REQUEST_STATUS_PENDING": ".user_access_request",
    "ACCESS_REQUEST_STATUSES": ".user_access_request",
    "UserActivity": ".user_activity",
    "Tag": ".metadata",
    "CARD_CLASSIFICATION_SOURCE_KIND_CHOICES": ".metadata",
    "CARD_CLASSIFICATION_SOURCE_TAG": ".metadata",
    "CARD_CLASSIFICATION_SOURCE_TYPE": ".metadata",
    "CARD_CLASSIFICATION_TARGET_FACTION": ".metadata",
    "CARD_CLASSIFICATION_TARGET_KIND_CHOICES": ".metadata",
    "CARD_CLASSIFICATION_TARGET_ROLE": ".metadata",
    "CardClassificationRule": ".metadata",
    "CardClassificationSourceKind": ".metadata",
    "CardClassificationTargetKind": ".metadata",
    "Symbol": ".metadata",
    "Keyword": ".metadata",
    "Type": ".metadata",
    "MetadataSuggestion": ".metadata",
    "CardVersionTag": ".metadata",
    "CardVersionSymbol": ".metadata",
    "CardVersionKeyword": ".metadata",
    "CardVersionType": ".metadata",
    "CardVersionMetadataSuggestion": ".metadata",
    "Template": ".template",
    "TTS_CARD_SHEET_CAPACITY": ".tts_card_sheet",
    "TTS_CARD_SHEET_COLUMNS": ".tts_card_sheet",
    "TTS_CARD_SHEET_LAYOUT_VERSION": ".tts_card_sheet",
    "TTS_CARD_SHEET_ROWS": ".tts_card_sheet",
    "TtsCardSheet": ".tts_card_sheet",
    "TtsCardSheetSlot": ".tts_card_sheet",
    "WorkerActivity": ".worker_heartbeat",
    "WorkerHeartbeat": ".worker_heartbeat",
}

__all__ = [
    "now_utc",
    "ImportJobStatus",
    "ImportClassificationMode",
    "CardClassificationInferenceEvidence",
    "CardFactionInferenceEvidence",
    "CardRoleInferenceEvidence",
    "ClassificationRuleEvidence",
    "ClassificationSourceEvidence",
    "ImportJob",
    "ImportJobItem",
    "Card",
    "ALL_CARD_POOLS_SCOPE",
    "CardBack",
    "CardAlias",
    "CardIdentityPoolLock",
    "BLOOD_CARD_FACTION",
    "BOON_CARD_ROLE",
    "BOSS_CARD_ROLE",
    "CARD_FACTION_CHOICES",
    "CARD_FACTION_DEFINITIONS",
    "CARD_FACTIONS",
    "CARD_POOL_CHOICES",
    "CARD_POOL_DEFINITIONS",
    "CARD_POOLS",
    "CARD_ROLE_CHOICES",
    "CARD_ROLE_DEFINITIONS",
    "CARD_ROLE_FILTER_DEFINITIONS",
    "CARD_ROLE_FILTER_VALUES",
    "CARD_ROLES",
    "DEFAULT_CARD_POOL",
    "DARKNESS_CARD_FACTION",
    "EVIL_CARD_POOL",
    "EVENT_CARD_ROLE",
    "HERO_CARD_ROLE",
    "LOCATION_CARD_ROLE",
    "NEUTRAL_CARD_POOL",
    "PLAYER_CARD_POOL",
    "PLAYER_CARD_POOL_SCOPE",
    "ORDER_CARD_FACTION",
    "SHOP_ITEM_CARD_ROLE",
    "STANDARD_CARD_ROLE",
    "ACTIVE_CARD_LIFECYCLE_STATUS",
    "ALL_CARD_LIFECYCLE_FILTER",
    "CARD_LIFECYCLE_FILTER_VALUES",
    "CARD_LIFECYCLE_STATUSES",
    "DEFAULT_CARD_LIFECYCLE_FILTER",
    "DEPRECATED_CARD_LIFECYCLE_STATUS",
    "CardLifecycleFilter",
    "CardLifecycleCarrier",
    "CardLifecycleStatus",
    "CardMergeRedirect",
    "CardPool",
    "CardPoolDefinition",
    "CardPoolScope",
    "CardFaction",
    "CardFactionAssignment",
    "CardFactionDefinition",
    "CardRole",
    "CardRoleAssignment",
    "CardRoleDefinition",
    "CardRoleFilter",
    "CardRoleFilterDefinition",
    "active_card_lifecycle_q",
    "card_faction_identity_key",
    "card_faction_keys",
    "card_has_faction",
    "card_has_role",
    "card_is_deprecated",
    "card_is_visible_for_lifecycle",
    "card_lifecycle_filter_q",
    "card_role_keys",
    "filter_queryset_by_card_lifecycle",
    "is_card_pool",
    "is_card_lifecycle_status",
    "normalize_card_lifecycle_filter",
    "normalize_card_factions",
    "normalize_card_roles",
    "CardGroup",
    "CardGroupMember",
    "ContentVersion",
    "CardVersion",
    "CardVersionImage",
    "ParseResult",
    "PARSE_FLAG_ITEM_DISMISSED",
    "PARSE_FLAG_ITEM_OPEN",
    "PARSE_FLAG_ITEM_RESOLVED",
    "PARSE_FLAG_ITEM_STATUSES",
    "PARSE_FLAG_PROPERTY_KEYS",
    "CardVersionParseFlag",
    "CardVersionParseFlagItem",
    "Deck",
    "DeckCreation",
    "DeckDifficulty",
    "DeckVisibility",
    "DeckEntry",
    "DeckSideboard",
    "DeckSideboardEntry",
    "DECK_TAG_KINDS",
    "DECK_TAG_SUGGESTION_STATUSES",
    "DeckTag",
    "DeckTagAssignment",
    "DeckTagKind",
    "DeckTagSuggestion",
    "DeckTagSuggestionDeck",
    "DeckTagSuggestionStatus",
    "DeveloperDataDownloadGrant",
    "DeveloperDataBuild",
    "DeveloperDataBuildStatus",
    "UserNotification",
    "NOTIFICATION_EVENT_DECK_CARD_VERSION_CHANGED",
    "NOTIFICATION_EVENT_PARSE_FLAG_ITEM_REVIEWED",
    "NOTIFICATION_STATUS_ALL",
    "NOTIFICATION_STATUS_FILTERS",
    "NOTIFICATION_STATUS_READ",
    "NOTIFICATION_STATUS_UNREAD",
    "UserAccessRequest",
    "ACCESS_REQUEST_STATUS_APPROVED",
    "ACCESS_REQUEST_STATUS_DECLINED",
    "ACCESS_REQUEST_STATUS_FILTER_ALL",
    "ACCESS_REQUEST_STATUS_FILTERS",
    "ACCESS_REQUEST_STATUS_PENDING",
    "ACCESS_REQUEST_STATUSES",
    "UserActivity",
    "Tag",
    "CARD_CLASSIFICATION_SOURCE_KIND_CHOICES",
    "CARD_CLASSIFICATION_SOURCE_TAG",
    "CARD_CLASSIFICATION_SOURCE_TYPE",
    "CARD_CLASSIFICATION_TARGET_FACTION",
    "CARD_CLASSIFICATION_TARGET_KIND_CHOICES",
    "CARD_CLASSIFICATION_TARGET_ROLE",
    "CardClassificationRule",
    "CardClassificationSourceKind",
    "CardClassificationTargetKind",
    "Symbol",
    "Keyword",
    "Type",
    "MetadataSuggestion",
    "CardVersionTag",
    "CardVersionSymbol",
    "CardVersionKeyword",
    "CardVersionType",
    "CardVersionMetadataSuggestion",
    "Template",
    "TTS_CARD_SHEET_CAPACITY",
    "TTS_CARD_SHEET_COLUMNS",
    "TTS_CARD_SHEET_LAYOUT_VERSION",
    "TTS_CARD_SHEET_ROWS",
    "TtsCardSheet",
    "TtsCardSheetSlot",
    "WorkerActivity",
    "WorkerHeartbeat",
]


def __getattr__(name: str) -> Any:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    return getattr(module, name)
