from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

# Import model modules eagerly so Django registers every model class when the
# app loads. The lazy export mechanism below is fine for attribute access, but
# not sufficient for ORM relation resolution across modules.
_REGISTERED_MODEL_MODULES = (
    import_module(".card", __name__),
    import_module(".card_back", __name__),
    import_module(".card_group", __name__),
    import_module(".content_version", __name__),
    import_module(".card_version", __name__),
    import_module(".parse_flag", __name__),
    import_module(".deck", __name__),
    import_module(".notification", __name__),
    import_module(".import_job", __name__),
    import_module(".metadata", __name__),
    import_module(".template", __name__),
)

if TYPE_CHECKING:
    from .base import now_utc
    from .card import (
        ACTIVE_CARD_LIFECYCLE_STATUS,
        ALL_CARD_LIFECYCLE_FILTER,
        CARD_LIFECYCLE_FILTER_VALUES,
        CARD_LIFECYCLE_STATUSES,
        DEFAULT_CARD_LIFECYCLE_FILTER,
        DEPRECATED_CARD_LIFECYCLE_STATUS,
        Card,
        CardAlias,
        CardLifecycleCarrier,
        CardLifecycleFilter,
        CardLifecycleStatus,
        CardMergeRedirect,
        active_card_lifecycle_q,
        card_is_deprecated,
        card_is_visible_for_lifecycle,
        card_lifecycle_filter_q,
        filter_queryset_by_card_lifecycle,
        is_card_lifecycle_status,
        normalize_card_lifecycle_filter,
    )
    from .card_back import CardBack
    from .card_group import CardGroup, CardGroupMember
    from .content_version import ContentVersion
    from .card_version import CardVersion, CardVersionImage, ParseResult
    from .parse_flag import (
        PARSE_FLAG_ITEM_DISMISSED,
        PARSE_FLAG_ITEM_OPEN,
        PARSE_FLAG_ITEM_RESOLVED,
        PARSE_FLAG_ITEM_STATUSES,
        PARSE_FLAG_PROPERTY_KEYS,
        CardVersionParseFlag,
        CardVersionParseFlagItem,
    )
    from .deck import Deck, DeckEntry, DeckSideboard, DeckSideboardEntry, DeckVisibility
    from .notification import (
        NOTIFICATION_EVENT_DECK_CARD_CHANGED,
        NOTIFICATION_EVENT_PARSE_FLAG_REVIEWED,
        NOTIFICATION_STATUS_ALL,
        NOTIFICATION_STATUS_FILTERS,
        NOTIFICATION_STATUS_READ,
        NOTIFICATION_STATUS_UNREAD,
        UserNotification,
    )
    from .import_job import ImportJob, ImportJobItem, ImportJobStatus
    from .metadata import (
        CardVersionMetadataSuggestion,
        CardVersionKeyword,
        CardVersionSymbol,
        CardVersionTag,
        CardVersionType,
        Keyword,
        MetadataSuggestion,
        Symbol,
        Tag,
        Type,
    )
    from .template import Template

_EXPORTS = {
    "now_utc": ".base",
    "ImportJobStatus": ".import_job",
    "ImportJob": ".import_job",
    "ImportJobItem": ".import_job",
    "Card": ".card",
    "CardBack": ".card_back",
    "CardAlias": ".card",
    "ACTIVE_CARD_LIFECYCLE_STATUS": ".card",
    "ALL_CARD_LIFECYCLE_FILTER": ".card",
    "CARD_LIFECYCLE_FILTER_VALUES": ".card",
    "CARD_LIFECYCLE_STATUSES": ".card",
    "DEFAULT_CARD_LIFECYCLE_FILTER": ".card",
    "DEPRECATED_CARD_LIFECYCLE_STATUS": ".card",
    "CardLifecycleFilter": ".card",
    "CardLifecycleCarrier": ".card",
    "CardLifecycleStatus": ".card",
    "CardMergeRedirect": ".card",
    "active_card_lifecycle_q": ".card",
    "card_is_deprecated": ".card",
    "card_is_visible_for_lifecycle": ".card",
    "card_lifecycle_filter_q": ".card",
    "filter_queryset_by_card_lifecycle": ".card",
    "is_card_lifecycle_status": ".card",
    "normalize_card_lifecycle_filter": ".card",
    "CardGroup": ".card_group",
    "CardGroupMember": ".card_group",
    "ContentVersion": ".content_version",
    "CardVersion": ".card_version",
    "CardVersionImage": ".card_version",
    "ParseResult": ".card_version",
    "PARSE_FLAG_ITEM_DISMISSED": ".parse_flag",
    "PARSE_FLAG_ITEM_OPEN": ".parse_flag",
    "PARSE_FLAG_ITEM_RESOLVED": ".parse_flag",
    "PARSE_FLAG_ITEM_STATUSES": ".parse_flag",
    "PARSE_FLAG_PROPERTY_KEYS": ".parse_flag",
    "CardVersionParseFlag": ".parse_flag",
    "CardVersionParseFlagItem": ".parse_flag",
    "Deck": ".deck",
    "DeckVisibility": ".deck",
    "DeckEntry": ".deck",
    "DeckSideboard": ".deck",
    "DeckSideboardEntry": ".deck",
    "UserNotification": ".notification",
    "NOTIFICATION_EVENT_DECK_CARD_CHANGED": ".notification",
    "NOTIFICATION_EVENT_PARSE_FLAG_REVIEWED": ".notification",
    "NOTIFICATION_STATUS_ALL": ".notification",
    "NOTIFICATION_STATUS_FILTERS": ".notification",
    "NOTIFICATION_STATUS_READ": ".notification",
    "NOTIFICATION_STATUS_UNREAD": ".notification",
    "Tag": ".metadata",
    "Symbol": ".metadata",
    "Keyword": ".metadata",
    "Type": ".metadata",
    "MetadataSuggestion": ".metadata",
    "CardVersionTag": ".metadata",
    "CardVersionSymbol": ".metadata",
    "CardVersionKeyword": ".metadata",
    "CardVersionType": ".metadata",
    "CardVersionMetadataSuggestion": ".metadata",
    "Template": ".template",
}

__all__ = [
    "now_utc",
    "ImportJobStatus",
    "ImportJob",
    "ImportJobItem",
    "Card",
    "CardBack",
    "CardAlias",
    "ACTIVE_CARD_LIFECYCLE_STATUS",
    "ALL_CARD_LIFECYCLE_FILTER",
    "CARD_LIFECYCLE_FILTER_VALUES",
    "CARD_LIFECYCLE_STATUSES",
    "DEFAULT_CARD_LIFECYCLE_FILTER",
    "DEPRECATED_CARD_LIFECYCLE_STATUS",
    "CardLifecycleFilter",
    "CardLifecycleCarrier",
    "CardLifecycleStatus",
    "CardMergeRedirect",
    "active_card_lifecycle_q",
    "card_is_deprecated",
    "card_is_visible_for_lifecycle",
    "card_lifecycle_filter_q",
    "filter_queryset_by_card_lifecycle",
    "is_card_lifecycle_status",
    "normalize_card_lifecycle_filter",
    "CardGroup",
    "CardGroupMember",
    "ContentVersion",
    "CardVersion",
    "CardVersionImage",
    "ParseResult",
    "PARSE_FLAG_ITEM_DISMISSED",
    "PARSE_FLAG_ITEM_OPEN",
    "PARSE_FLAG_ITEM_RESOLVED",
    "PARSE_FLAG_ITEM_STATUSES",
    "PARSE_FLAG_PROPERTY_KEYS",
    "CardVersionParseFlag",
    "CardVersionParseFlagItem",
    "Deck",
    "DeckVisibility",
    "DeckEntry",
    "DeckSideboard",
    "DeckSideboardEntry",
    "UserNotification",
    "NOTIFICATION_EVENT_DECK_CARD_CHANGED",
    "NOTIFICATION_EVENT_PARSE_FLAG_REVIEWED",
    "NOTIFICATION_STATUS_ALL",
    "NOTIFICATION_STATUS_FILTERS",
    "NOTIFICATION_STATUS_READ",
    "NOTIFICATION_STATUS_UNREAD",
    "Tag",
    "Symbol",
    "Keyword",
    "Type",
    "MetadataSuggestion",
    "CardVersionTag",
    "CardVersionSymbol",
    "CardVersionKeyword",
    "CardVersionType",
    "CardVersionMetadataSuggestion",
    "Template",
]


def __getattr__(name: str) -> Any:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    return getattr(module, name)
