from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS = {
    "SUPPORTED_IMAGE_SUFFIXES": ".import_jobs_repository",
    "collect_supported_files": ".import_jobs_repository",
    "list_import_jobs": ".import_jobs_repository",
    "create_import_job": ".import_jobs_repository",
    "mark_job_running": ".import_jobs_repository",
    "mark_job_queued": ".import_jobs_repository",
    "mark_job_complete": ".import_jobs_repository",
    "mark_job_failed": ".import_jobs_repository",
    "bump_job_processed": ".import_jobs_repository",
    "fetch_job": ".import_jobs_repository",
    "fetch_items_for_job": ".import_jobs_repository",
    "get_next_queued_job": ".import_jobs_repository",
    "mark_job_item_failed": ".import_jobs_repository",
    "requeue_running_import_jobs": ".import_jobs_repository",
    "save_parsed_card": ".cards_repository",
    "list_cards": ".cards_repository",
    "list_matching_cards": ".cards_repository",
    "get_card": ".cards_repository",
    "get_latest_card_version": ".cards_repository",
    "get_card_image": ".cards_repository",
    "resolve_image_file_path": ".cards_repository",
    "list_card_generations": ".cards_repository",
    "update_latest_card_version": ".cards_repository",
    "decode_field_sources": ".cards_repository",
    "decode_parsed_snapshot": ".cards_repository",
    "card_group_key_exists": ".card_groups_repository",
    "create_card_group": ".card_groups_repository",
    "delete_card_group": ".card_groups_repository",
    "get_card_group": ".card_groups_repository",
    "get_cards": ".card_groups_repository",
    "list_card_groups": ".card_groups_repository",
    "list_card_groups_for_card": ".card_groups_repository",
    "list_card_groups_for_cards": ".card_groups_repository",
    "replace_card_group_members": ".card_groups_repository",
    "update_card_group": ".card_groups_repository",
    "get_cards_by_ids": ".decks_repository",
    "list_public_decks": ".decks_repository",
    "list_owner_decks": ".decks_repository",
    "get_public_deck": ".decks_repository",
    "get_owner_deck": ".decks_repository",
    "get_deck_for_viewer": ".decks_repository",
    "create_deck": ".decks_repository",
    "update_deck": ".decks_repository",
    "delete_deck": ".decks_repository",
    "replace_deck_entries": ".decks_repository",
    "export_cards_csv": ".exports_repository",
    "normalize_slug_key": ".helpers",
    "list_keywords": ".metadata_repository",
    "list_tags": ".metadata_repository",
    "list_symbols": ".metadata_repository",
    "list_types": ".metadata_repository",
    "list_detectable_symbols": ".metadata_repository",
    "get_keyword": ".metadata_repository",
    "get_tag": ".metadata_repository",
    "get_symbol": ".metadata_repository",
    "get_type": ".metadata_repository",
    "get_metadata_suggestion": ".metadata_repository",
    "keyword_key_exists": ".metadata_repository",
    "tag_key_exists": ".metadata_repository",
    "symbol_key_exists": ".metadata_repository",
    "type_key_exists": ".metadata_repository",
    "create_keyword": ".metadata_repository",
    "create_tag": ".metadata_repository",
    "create_symbol": ".metadata_repository",
    "create_type": ".metadata_repository",
    "update_keyword": ".metadata_repository",
    "update_tag": ".metadata_repository",
    "update_symbol": ".metadata_repository",
    "update_type": ".metadata_repository",
    "delete_keyword": ".metadata_repository",
    "delete_tag": ".metadata_repository",
    "delete_symbol": ".metadata_repository",
    "delete_type": ".metadata_repository",
    "replace_card_version_keywords": ".metadata_repository",
    "replace_card_version_symbols": ".metadata_repository",
    "replace_card_version_tags": ".metadata_repository",
    "replace_card_version_types": ".metadata_repository",
    "replace_card_version_metadata_suggestions": ".metadata_repository",
    "get_keywords_for_card_version": ".metadata_repository",
    "get_tags_for_card_version": ".metadata_repository",
    "get_symbols_for_card_version": ".metadata_repository",
    "get_types_for_card_version": ".metadata_repository",
    "get_or_create_metadata_suggestion": ".metadata_repository",
    "list_metadata_suggestions": ".metadata_repository",
    "list_card_version_suggestion_occurrences": ".metadata_repository",
    "SuggestionCandidate": ".metadata_repository",
    "MetadataSuggestionListRow": ".metadata_repository",
    "list_templates": ".templates_repository",
    "get_template": ".templates_repository",
    "get_template_by_key": ".templates_repository",
    "template_key_exists": ".templates_repository",
    "create_template": ".templates_repository",
    "update_template": ".templates_repository",
    "delete_template": ".templates_repository",
}

__all__ = list(_EXPORTS)


def __getattr__(name: str) -> Any:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    return getattr(module, name)
