from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .cards_repository import (
        get_card,
        get_card_image,
        get_latest_card_version,
        list_card_generations,
        list_cards,
        save_parsed_card,
        update_card,
    )
    from .exports_repository import export_cards_csv
    from .helpers import normalize_slug_key
    from .import_jobs_repository import (
        SUPPORTED_IMAGE_SUFFIXES,
        bump_job_processed,
        collect_supported_files,
        create_import_job,
        fetch_items_for_job,
        fetch_job,
        get_job_items,
        get_next_queued_job,
        list_import_jobs,
        mark_job_complete,
        mark_job_failed,
        mark_job_item_failed,
        mark_job_queued,
        mark_job_running,
        requeue_running_import_jobs,
    )
    from .metadata_repository import (
        create_keyword,
        create_symbol,
        create_tag,
        create_type,
        delete_keyword,
        delete_symbol,
        delete_tag,
        delete_type,
        get_keyword,
        get_keywords_for_card_version,
        get_symbol,
        get_symbols_for_card_version,
        get_tag,
        get_tags_for_card_version,
        get_type,
        get_types_for_card_version,
        keyword_key_exists,
        list_detectable_symbols,
        list_keywords,
        list_symbols,
        list_tags,
        list_types,
        replace_card_version_keywords,
        replace_card_version_symbols,
        replace_card_version_tags,
        replace_card_version_types,
        symbol_key_exists,
        tag_key_exists,
        type_key_exists,
        update_keyword,
        update_symbol,
        update_tag,
        update_type,
        upsert_tags_by_labels,
        upsert_types_by_labels,
    )
    from .templates_repository import (
        create_template,
        delete_template,
        get_template,
        get_template_by_key,
        list_templates,
        template_key_exists,
        update_template,
    )

_EXPORTS = {
    "SUPPORTED_IMAGE_SUFFIXES": ".import_jobs_repository",
    "collect_supported_files": ".import_jobs_repository",
    "list_import_jobs": ".import_jobs_repository",
    "create_import_job": ".import_jobs_repository",
    "mark_job_running": ".import_jobs_repository",
    "mark_job_queued": ".import_jobs_repository",
    "mark_job_complete": ".import_jobs_repository",
    "mark_job_failed": ".import_jobs_repository",
    "bump_job_processed": ".import_jobs_repository",
    "fetch_job": ".import_jobs_repository",
    "fetch_items_for_job": ".import_jobs_repository",
    "get_next_queued_job": ".import_jobs_repository",
    "get_job_items": ".import_jobs_repository",
    "mark_job_item_failed": ".import_jobs_repository",
    "requeue_running_import_jobs": ".import_jobs_repository",
    "save_parsed_card": ".cards_repository",
    "list_cards": ".cards_repository",
    "get_card": ".cards_repository",
    "get_latest_card_version": ".cards_repository",
    "get_card_image": ".cards_repository",
    "list_card_generations": ".cards_repository",
    "update_card": ".cards_repository",
    "export_cards_csv": ".exports_repository",
    "normalize_slug_key": ".helpers",
    "list_keywords": ".metadata_repository",
    "list_tags": ".metadata_repository",
    "list_symbols": ".metadata_repository",
    "list_types": ".metadata_repository",
    "list_detectable_symbols": ".metadata_repository",
    "get_keyword": ".metadata_repository",
    "get_tag": ".metadata_repository",
    "get_symbol": ".metadata_repository",
    "get_type": ".metadata_repository",
    "keyword_key_exists": ".metadata_repository",
    "tag_key_exists": ".metadata_repository",
    "symbol_key_exists": ".metadata_repository",
    "type_key_exists": ".metadata_repository",
    "create_keyword": ".metadata_repository",
    "create_tag": ".metadata_repository",
    "create_symbol": ".metadata_repository",
    "create_type": ".metadata_repository",
    "update_keyword": ".metadata_repository",
    "update_tag": ".metadata_repository",
    "update_symbol": ".metadata_repository",
    "update_type": ".metadata_repository",
    "delete_keyword": ".metadata_repository",
    "delete_tag": ".metadata_repository",
    "delete_symbol": ".metadata_repository",
    "delete_type": ".metadata_repository",
    "replace_card_version_keywords": ".metadata_repository",
    "replace_card_version_symbols": ".metadata_repository",
    "replace_card_version_tags": ".metadata_repository",
    "replace_card_version_types": ".metadata_repository",
    "upsert_tags_by_labels": ".metadata_repository",
    "upsert_types_by_labels": ".metadata_repository",
    "get_keywords_for_card_version": ".metadata_repository",
    "get_tags_for_card_version": ".metadata_repository",
    "get_symbols_for_card_version": ".metadata_repository",
    "get_types_for_card_version": ".metadata_repository",
    "list_templates": ".templates_repository",
    "get_template": ".templates_repository",
    "get_template_by_key": ".templates_repository",
    "template_key_exists": ".templates_repository",
    "create_template": ".templates_repository",
    "update_template": ".templates_repository",
    "delete_template": ".templates_repository",
}

__all__ = list(_EXPORTS)


def __getattr__(name: str) -> Any:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    return getattr(module, name)
