services:
  api:
    volumes:
      - type: bind
        source: ${CARD_READER_HOST_APP_DATA_DIR:?Set CARD_READER_HOST_APP_DATA_DIR}
        target: /var/lib/card-reader
      - type: bind
        source: ${CARD_READER_HOST_PUBLIC_APP_DATA_DIR:?Set CARD_READER_HOST_PUBLIC_APP_DATA_DIR}/images
        target: /var/lib/card-reader/images
      - type: bind
        source: ${CARD_READER_HOST_PUBLIC_APP_DATA_DIR:?Set CARD_READER_HOST_PUBLIC_APP_DATA_DIR}/symbols
        target: /var/lib/card-reader/symbols

  developer-data-builder:
    volumes:
      - type: bind
        source: ${CARD_READER_HOST_APP_DATA_DIR:?Set CARD_READER_HOST_APP_DATA_DIR}
        target: /var/lib/card-reader
      - type: bind
        source: ${CARD_READER_HOST_PUBLIC_APP_DATA_DIR:?Set CARD_READER_HOST_PUBLIC_APP_DATA_DIR}/images
        target: /var/lib/card-reader/images
      - type: bind
        source: ${CARD_READER_HOST_PUBLIC_APP_DATA_DIR:?Set CARD_READER_HOST_PUBLIC_APP_DATA_DIR}/symbols
        target: /var/lib/card-reader/symbols

  parser:
    volumes:
      - type: bind
        source: ${CARD_READER_HOST_APP_DATA_DIR:?Set CARD_READER_HOST_APP_DATA_DIR}
        target: /var/lib/card-reader
      - type: bind
        source: ${CARD_READER_HOST_PUBLIC_APP_DATA_DIR:?Set CARD_READER_HOST_PUBLIC_APP_DATA_DIR}/images
        target: /var/lib/card-reader/images
      - type: bind
        source: ${CARD_READER_HOST_PUBLIC_APP_DATA_DIR:?Set CARD_READER_HOST_PUBLIC_APP_DATA_DIR}/symbols
        target: /var/lib/card-reader/symbols
