services:
  api:
    volumes: !override
      - card_reader_data:/var/lib/card-reader

  developer-data-builder:
    volumes: !override
      - card_reader_data:/var/lib/card-reader

  parser:
    volumes: !override
      - card_reader_data:/var/lib/card-reader

volumes:
  card_reader_data:
