export const MIN_MAINBOARD_CARD_COUNT = 20;
export const MAX_MAINBOARD_CARD_COUNT = 100;
export const MIN_MAINBOARD_MANA_TYPE_COUNT = 3;
export const MAX_DECK_COPIES = 4;
export const MAX_SIDEBOARD_ENTRY_QUANTITY = 100;
