from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card_reader_core", "0012_relativize_symbol_asset_paths"),
    ]

    operations = [
        migrations.RenameField(
            model_name="importjobitem",
            old_name="job_id",
            new_name="job",
        ),
        migrations.RenameField(
            model_name="cardversion",
            old_name="parse_result_id",
            new_name="parse_result",
        ),
        migrations.AlterField(
            model_name="importjob",
            name="options_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="importjobitem",
            name="job",
            field=models.ForeignKey(
                db_column="job_id",
                on_delete=models.deletion.CASCADE,
                related_name="items",
                to="card_reader_core.importjob",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="definition_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="tag",
            name="identifiers_json",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="identifiers_json",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="type",
            name="identifiers_json",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="detection_config_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="reference_assets_json",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="cardversion",
            name="mana_symbols_json",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="cardversion",
            name="field_sources_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="cardversion",
            name="parsed_snapshot_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="cardversion",
            name="parse_result",
            field=models.ForeignKey(
                db_column="parse_result_id",
                default=None,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="+",
                to="card_reader_core.parseresult",
            ),
        ),
        migrations.AlterField(
            model_name="parseresult",
            name="raw_ocr_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="parseresult",
            name="normalized_fields_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="parseresult",
            name="confidence_json",
            field=models.JSONField(default=dict),
        ),
    ]
