# Generated by Django 6.0.4 on 2026-06-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_reader_core', '0032_deck_entry_positions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deckentry',
            options={'ordering': ['position', 'card_id']},
        ),
        migrations.AlterModelOptions(
            name='decksideboardentry',
            options={'ordering': ['position', 'card_id']},
        ),
    ]
