# Generated by Codex on 2026-06-13

import card_reader_core.models.base
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("card_reader_core", "0033_alter_deckentry_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardBack",
            fields=[
                ("created_at", models.DateTimeField(default=card_reader_core.models.base.now_utc)),
                ("updated_at", models.DateTimeField(default=card_reader_core.models.base.now_utc)),
                (
                    "id",
                    models.TextField(
                        default=card_reader_core.models.base.uuid_str,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.TextField(default="")),
                ("original_filename", models.TextField(default="")),
                ("source_file", models.TextField()),
                ("stored_path", models.TextField()),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("checksum", models.TextField(db_index=True)),
                ("is_current", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "db_table": "card_back",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="cardback",
            constraint=models.UniqueConstraint(
                condition=Q(is_current=True),
                fields=("is_current",),
                name="ux_card_back_single_current",
            ),
        ),
    ]
