# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_reader_core", "0034_card_back"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cardversionimage",
            index=models.Index(
                fields=["card_version", "-created_at"],
                name="ix_cv_image_version_created",
            ),
        ),
        migrations.AddIndex(
            model_name="cardversionkeyword",
            index=models.Index(
                fields=["keyword", "card_version"],
                name="ix_cv_keyword_keyword_version",
            ),
        ),
        migrations.AddIndex(
            model_name="cardversionsymbol",
            index=models.Index(
                fields=["symbol", "card_version"],
                name="ix_cv_symbol_symbol_version",
            ),
        ),
        migrations.AddIndex(
            model_name="cardversiontag",
            index=models.Index(
                fields=["tag", "card_version"],
                name="ix_cv_tag_tag_version",
            ),
        ),
        migrations.AddIndex(
            model_name="cardversiontype",
            index=models.Index(
                fields=["type", "card_version"],
                name="ix_cv_type_type_version",
            ),
        ),
    ]
